### ISSUE TITLE
hdr()$hdr sometimes contains only left bound, sometimes only right bound

### ISSUE THREAD

**Issue by hughjonesd** [robjhyndman/hdrcde#3] opened 2018-11-03 08:24 UTC
Examples:

```
# right bound only
hdrcde::hdr(den = list(x = x<- 0:100/100, y = dbeta(x, 1, 2)), prob = 99)$hdr
    [,1]
99%  0.9

# left bound only
hdrcde::hdr(den = list(x = x<- 0:10000/10000, y = dbeta(x, 2, 1)), prob = 99)$hdr
        [,1]
99% 0.107195
```

This means consuming code has to guess which interval is which. A workaround is to include e.g. `prob = c(99, 0.01)`. 

My version: 3.2 from github.

**Comment by robjhyndman** [comment] 2018-11-04 21:45
The "workaround" does not fix the issue. The problem is that the densities provided are essentially triangular. 

```r
x <- seq(0,1,l=1000)
hdrcde::hdr.den(den = list(x = x, y = dbeta(x, 1, 2)), prob = 99)$hdr
hdrcde::hdr.den(den = list(x = x, y = dbeta(x, 2, 1)), prob = 99)$hdr
```

The function does not know what happens to the density outside the range (0,1). The best solution is to expand the range slightly.

```r
x <- seq(-0.01,1.01,l=1000)
hdrcde::hdr(den = list(x = x, y = dbeta(x, 1, 2)), prob = 99)$hdr
hdrcde::hdr(den = list(x = x, y = dbeta(x, 2, 1)), prob = 99)$hdr
```

**Comment by hughjonesd** [comment] 2018-11-04 23:12
I see. But if I include the second density, it does solve part of my problem, because I get a NA back, instead of just a single column without a name. So then at least I know which bound could not be determined.

So I think there are two issues here: the not knowing what the density is at 0 and 1; and the fact that only one column is returned when only one `prob` is requested.

**Comment by vittorioorlandi** [comment] 2020-10-20 13:56
I'm having this same problem, with 3 or sometimes 5 endpoints being returned. However, the density is smooth (I've even had this problem with practically normal densities), the probability is 0.95 (not very close to 1), and the HDR intervals should not (as far as I can tell) go beyond the range of the data.

I've attached a reproducible example. 
[hdrcde_bug.R.zip](https://github.com/robjhyndman/hdrcde/files/5409156/hdrcde_bug.R.zip)

**Comment by robjhyndman** [comment] 2020-10-21 04:06
All these problems should now be fixed in the latest commit: https://github.com/robjhyndman/hdrcde/commit/3db6f9bb4138c9f3f1c080ba458c53cff57526d3

**Closed as completed** 2020-11-22 23:39 UTC
